version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  # urban_fiesta:
  #   build: .
  #   container_name: urbaniestaAPI
  #   restart: on-failure
  #   ports:
  #     - 5000:5000
  #     - 5001:5001