CREATE TABLE public."Events" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"local" text NOT NULL,
	"description" text NULL,
	"ageLimit" int4 NOT NULL DEFAULT 0,
	"date" timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
	"eventPhoto" text NULL,
	finish timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
	"name" text NOT NULL DEFAULT ''::text,
	price float4 NOT NULL DEFAULT 0,
	"start" timestamp NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp without time zone,
	tag text NULL,
	CONSTRAINT "PK_Events" PRIMARY KEY (id)
);

CREATE TABLE public."Tickets" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL,
	price float4 NOT NULL,
	"dateTime" timestamp NOT NULL,
	CONSTRAINT "PK_Tickets" PRIMARY KEY (id)
);